---
include:
  - template: Security/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

variables:
  KUBE_CTX: homelab
  TF_IMPLICIT_INIT: "true"
  TF_STATE_NAME: prod

stages: [test, validate, build, deploy, cleanup]

default:
  image: registry.gitlab.com/containers1211942/opentofu

fmt:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  allow_failure: true
  cache:
    key: ${CI_PROJECT_DIR}
    paths:
      - ${CI_PROJECT_DIR}/.terraform
  script:
    - gitlab-tofu fmt

validate:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  cache:
    key: ${CI_PROJECT_DIR}
    paths:
      - ${CI_PROJECT_DIR}/.terraform
  before_script:
    - gitlab-tofu init --upgrade
  script:
    - gitlab-tofu validate
