---
include:
  - template: Security/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

variables:
  KUBE_CTX: homelab

stages: [validate, test, build, deploy, cleanup]

default:
  image: registry.gitlab.com/containers1211942/opentofu
  before_script:
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - kubectl config get-contexts

fmt:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  allow_failure: true
  cache:
    key: ${CI_PROJECT_DIR}
    paths:
      - ${CI_PROJECT_DIR}/.terraform
  script:
    - gitlab-tofu fmt
